# Generated by Django 4.0.1 on 2024-06-02 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='timeSlotId',
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeSlot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment_service.timeslot'),
        ),
    ]
