# Generated by Django 4.0.1 on 2024-06-02 00:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(null=True)),
                ('diagnosis', models.TextField(null=True)),
            ],
            options={
                'db_table': 'medical_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('indication', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('treatment', models.TextField()),
                ('amount', models.IntegerField()),
                ('medicalRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='medical_service.medicalrecord')),
                ('medical_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_service.medication')),
            ],
            options={
                'db_table': 'medical_record_detail',
            },
        ),
    ]
