# Generated by Django 4.0.1 on 2024-06-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecorddetail',
            old_name='medical_id',
            new_name='medical',
        ),
    ]
