# Generated by Django 4.0.1 on 2024-06-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('doctor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
